### ISSUE TITLE
Node server.js

### ISSUE THREAD

**Issue by rickytranmer** [rover33/Holistic-Blog#161]
I tried to run it on localhost but 'node server.js' gave me 'Error: Dialect needs to be explicitly supplied as of v4.0.0'.  I think Aaron had a similar issue and may be able to send you a solution.

**Comment by milad-abujarada** [comment]
Ricky needs to create his own postgreSQL database and add connection to it in /models/index.js. Also Ricky needs to stop buying our shit. I'm gonna come after you RICKY
